#!/usr/bin/env node
/**
 * Generates high-quality responsive AVIF/WebP variants for local images.
 * Source images are kept untouched; the site consumes files from /optimized.
 */
const fs = require('fs');
const path = require('path');
const sharp = require('sharp');

const root = path.join(__dirname, '..');
const outputRoot = path.join(root, 'optimized');
const manifestPath = path.join(root, 'js', 'image-manifest.js');

const imageExts = new Set(['.jpg', '.jpeg', '.png', '.webp']);
const skipDirs = new Set(['.git', '.wrangler', 'dist', 'node_modules', 'optimized']);
const photoWidths = [400, 800, 1200, 1600];
const graphicWidths = [96, 160, 240, 360];

function toPosix(filePath) {
  return filePath.split(path.sep).join('/');
}

function urlFor(relativeFile) {
  return '/' + relativeFile.split('/').map(encodeURIComponent).join('/');
}

function shouldSkipFile(relativeFile) {
  if (relativeFile === 'dark_logo_big3d.jpg') return true; // Legacy source; the WebP logo is the canonical source.
  if (relativeFile.startsWith('scripts/') || relativeFile.startsWith('src/')) return true;
  return false;
}

function collectImages(dir, result = []) {
  for (const entry of fs.readdirSync(dir)) {
    if (skipDirs.has(entry)) continue;
    const full = path.join(dir, entry);
    const stat = fs.statSync(full);
    if (stat.isDirectory()) {
      collectImages(full, result);
      continue;
    }

    const ext = path.extname(entry).toLowerCase();
    const relative = toPosix(path.relative(root, full));
    if (imageExts.has(ext) && !shouldSkipFile(relative)) {
      result.push(full);
    }
  }
  return result;
}

function variantsFor(relative, width) {
  const isGraphic =
    relative.startsWith('icons/') ||
    relative.includes('logo') ||
    relative === 'dark_logo_big3d.webp';
  const widths = isGraphic ? graphicWidths : photoWidths;
  const selected = widths.filter(w => w <= width);
  if (!selected.length) selected.push(Math.min(width, widths[0]));
  if (!selected.includes(width) && width < widths[widths.length - 1]) {
    selected.push(width);
  }
  return [...new Set(selected)].sort((a, b) => a - b);
}

async function writeVariant(source, relative, width, format) {
  const parsed = path.parse(relative);
  const outputRelative = toPosix(path.join(
    'optimized',
    parsed.dir,
    `${parsed.name}-${width}.${format}`
  ));
  const outputPath = path.join(root, outputRelative);
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });

  const isGraphic = relative.startsWith('icons/') || relative.includes('logo');
  let pipeline = sharp(source)
    .rotate()
    .resize({
      width,
      withoutEnlargement: true,
      fit: 'inside',
    });

  if (format === 'avif') {
    pipeline = pipeline.avif({
      quality: isGraphic ? 72 : 62,
      effort: 6,
      chromaSubsampling: isGraphic ? '4:4:4' : '4:2:0',
    });
  } else {
    pipeline = pipeline.webp({
      quality: isGraphic ? 90 : 84,
      effort: 6,
      smartSubsample: true,
    });
  }

  await pipeline.toFile(outputPath);
  return { width, url: urlFor(outputRelative), bytes: fs.statSync(outputPath).size };
}

async function main() {
  if (fs.existsSync(outputRoot)) fs.rmSync(outputRoot, { recursive: true, force: true });
  fs.mkdirSync(outputRoot, { recursive: true });

  const files = collectImages(root);
  const manifest = {};
  let sourceBytes = 0;
  let optimizedBytes = 0;
  let variantCount = 0;

  for (const file of files) {
    const relative = toPosix(path.relative(root, file));
    const meta = await sharp(file).metadata();
    if (!meta.width || !meta.height) continue;

    const originalBytes = fs.statSync(file).size;
    sourceBytes += originalBytes;
    const widths = variantsFor(relative, meta.width);
    const avif = [];
    const webp = [];

    for (const width of widths) {
      const avifVariant = await writeVariant(file, relative, width, 'avif');
      const webpVariant = await writeVariant(file, relative, width, 'webp');
      avif.push(avifVariant);
      webp.push(webpVariant);
      optimizedBytes += avifVariant.bytes + webpVariant.bytes;
      variantCount += 2;
    }

    const fallback =
      webp.find(item => item.width >= Math.min(meta.width, 800)) ||
      webp[webp.length - 1];

    manifest[relative] = {
      width: meta.width,
      height: meta.height,
      original: urlFor(relative),
      fallback: fallback.url,
      avif,
      webp,
    };
  }

  const js = `// Auto-generated by scripts/optimize-images.js\nwindow.OPTIMIZED_IMAGES = ${JSON.stringify(manifest, null, 2)};\n`;
  fs.writeFileSync(manifestPath, js);

  console.log(`✅ Optimized ${files.length} images into ${variantCount} AVIF/WebP variants`);
  console.log(`Source images: ${(sourceBytes / 1024 / 1024).toFixed(2)} MB`);
  console.log(`Generated variants: ${(optimizedBytes / 1024 / 1024).toFixed(2)} MB`);
  console.log('Manifest: js/image-manifest.js');
}

main().catch(error => {
  console.error(error);
  process.exit(1);
});
